version: "3.8"

services:
  jupyter:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8888:8888"
    volumes:
      # - ../:/app
      - ../src:/app/src
      - ../datasets:/app/datasets
      - ../requirements.txt:/app/requirements.txt
    environment:
      - JUPYTER_ENABLE_LAB=yes
